name: CI testing

on: [push, pull_request]

jobs:
  generate-lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install pip-tools
        run: pip install pip-tools
      - name: Generate requirements.lock
        run: pip-compile requirements.in -o requirements.lock
      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: requirements-lock-file
          path: requirements.lock

  training-test:
    needs: generate-lockfile
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12', '3.13']

    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Download lockfile
        uses: actions/download-artifact@v4
        with:
          name: requirements-lock-file
      - name: Install dependencies
        run: pip install -r requirements.lock
      - name: Training test
        shell: bash
        run: |
          # Launch cartpole experiment and store the last reward of the training
          python muzero.py cartpole '{"training_steps": 7500}' 2>&1 | tee log.txt
      - name: Archive log artifact
        uses: actions/upload-artifact@v4
        with:
          name: training_test_logs_${{ matrix.python-version }}
          path: log.txt
      - name: Retrieve training test log
        uses: actions/download-artifact@v4
        with:
          name: training_test_logs_${{ matrix.python-version }}
      - name: Check reward
        shell: bash
        run: |
          # Retrieve last reward
          BEST_REWARD=$(cat log.txt | sed -n -E 's/^.*reward: ([0-9]+).*$/\1/p' | sort -n | tail -1)
          # Display best reward
          echo "Best reward of cartpole training: " $BEST_REWARD
          # Validate reward value
          if ((BEST_REWARD < 250)); then
            exit 1
          fi
