name: Main CI

on: [push, pull_request]

jobs:
  run-all-tests:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11', '3.12', '3.13']
    uses: ./.github/workflows/reusable-test-workflow.yaml
    with:
      python-version: ${{ matrix.python-version }}
