name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.python-version >= '3.12' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install legacy dependencies (<= 3.9)
        if: ${{ inputs.python-version <= '3.9' }}
        run: |
          pip install --upgrade 'pip<22'
          pip install 'setuptools<58'
          pip install -r requirements.lock
          pip install --force-reinstall 'aiohttp==3.7.4'
          pip install 'ray[default]'

      - name: Install modern dependencies (>= 3.10)
        if: ${{ inputs.python-version >= '3.10' }}
        run: pip install -r requirements.in

      - name: Training test
        shell: bash
        run: |
          # Launch cartpole experiment and store the last reward of the training
          python muzero.py cartpole '{"training_steps": 7500}' 2>&1 | tee log.txt

      - name: Check reward
        shell: bash
        run: |
          # Retrieve last reward
          BEST_REWARD=$(cat log.txt | sed -n -E 's/^.*reward: ([0-9]+).*$/\1/p' | sort -n | tail -1)

          # Display best reward
          echo "Best reward of cartpole training: " $BEST_REWARD

          # Validate reward value
          if ((BEST_REWARD < 250)); then
            exit 1
          fi

      - name: Archive log artifact
        uses: actions/upload-artifact@v4
        with:
          name: training_test_logs_${{ inputs.python-version }}
          path: log.txt
